#SIZE
WIDTH = 10
HEIGHT = 10
SCALE = 40
RADIUS = 5
ELEMENT_SIZE = 38
#SPEED
FPS = 60
INITIAL_SPEED_DELAY = FPS // 2
#COLORS
SNAKE_COLOR = "yellow"
APPLE_COLOR = "red"
SCORE_COLOR = "white"
SCREEN_COLOR = "black"
GAME_OVER_COLOR = "red"
SIMPLE_TEXT_COLOR='white'